# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppMusic' do
	# Comment the next line if you don't want to use dynamic frameworks
	use_frameworks!
	pod 'SNCollectionViewLayout'
	pod 'Alamofire', '~> 5.0'
	pod 'RxSwift', '~> 5'
	pod 'RxCocoa', '~> 5'
	pod 'RealmSwift'
	pod 'Socket.IO-Client-Swift', '~> 15.2.0'
	pod 'SnapKit', '~> 5.0.0'
	pod 'SwiftGifOrigin', '~> 1.7.0'
	# Pods for AppMusic
	
end
